# Generated by Django 4.2.24 on 2026-03-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_product_google_merchant_fields_remove_category_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='cat_active_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='prod_active_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='prod_active_stock_idx',
        ),
    ]
