# Generated by Django 4.2.24 on 2026-03-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_crm_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('pending_payment', 'Очікує оплати'), ('paid', 'Оплачено'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано'), ('refund', 'Повернення'), ('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
