# Generated by Django 4.2.24 on 2026-03-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expand_sitesettings_universal_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='GORDI market', help_text='Відображається в заголовках, логотипі та мета-тегах', max_length=100, verbose_name='Назва магазину'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_color',
            field=models.CharField(default='#1a1a1a', help_text='Використовується в meta theme-color для мобільних браузерів', max_length=7, verbose_name='Колір теми (HEX)'),
        ),
    ]
